spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:backend.db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    with-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
